import { CATEGORY, STAGE_STYLES } from "../lib/constants.js";
import ScoreBar from "./ScoreBar.jsx";

function formatMarkdownReport(form, mapData) {
  const lines = [];
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  lines.push(`# Talent Landscape Report`);
  lines.push(`**Role:** ${form.role}${form.seniority ? ` (${form.seniority})` : ""}`);
  if (form.company) lines.push(`**Hiring Company:** ${form.company}`);
  if (form.location) lines.push(`**Location:** ${form.location}`);
  if (form.skills.length) lines.push(`**Skills:** ${form.skills.join(", ")}`);
  lines.push(`**Generated:** ${date}`);
  lines.push("");

  const sections = [
    { key: "companies", title: "Target Companies" },
    { key: "adjacent", title: "Adjacent Talent Pools" },
    { key: "wildcards", title: "Wildcard Bets" },
    { key: "titles", title: "Target Titles" },
  ];

  for (const sec of sections) {
    const nodes = mapData[sec.key];
    if (!nodes?.length) continue;
    lines.push(`## ${sec.title}`);
    for (const n of nodes) {
      lines.push(`- **${n.label}**${n.stage ? ` [${n.stage}]` : ""} — ${n.sub || ""}`);
      if (n.confidence != null) lines.push(`  - Confidence: ${n.confidence}%`);
      if (n.poachability != null) lines.push(`  - Poachability: ${n.poachability}%`);
      if (n.talentDensity != null) lines.push(`  - Talent Density: ${n.talentDensity}%`);
      if (n.likelyProfile) lines.push(`  - Profile: ${n.likelyProfile}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by Sourcing Compass — AI-powered talent intelligence. Verify before outreach.*");
  return lines.join("\n");
}

function ReportSection({ title, catKey, nodes }) {
  const cat = CATEGORY[catKey];
  if (!nodes?.length) return null;

  return (
    <div className="mb-8">
      <div className="flex items-center gap-2.5 mb-3 pb-2 border-b border-gray-200">
        <div className={`w-2 h-2 rounded-full ${cat.dot}`} />
        <h3 className={`text-sm font-semibold uppercase tracking-wide ${cat.text}`}>{title}</h3>
        <span className="text-xs text-gray-400 ml-auto">{nodes.length}</span>
      </div>
      <div className="space-y-3">
        {nodes.map((node) => (
          <div key={node.id} className="flex gap-4 py-2">
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-0.5">
                <span className="text-sm font-semibold text-gray-900">{node.label}</span>
                {node.stage && (
                  <span className={`text-[10px] px-2 py-0.5 rounded-full border font-medium ${STAGE_STYLES[node.stage] || "bg-gray-100 text-gray-600 border-gray-200"}`}>
                    {node.stage}
                  </span>
                )}
              </div>
              {node.sub && <div className="text-xs text-gray-500 mb-1">{node.sub}</div>}
              {node.likelyProfile && (
                <div className="text-xs text-gray-600 italic">{node.likelyProfile}</div>
              )}
            </div>
            <div className="w-36 flex-shrink-0 space-y-1">
              {node.confidence != null && (
                <ScoreBar label="Confidence" value={node.confidence} color="#10b981" />
              )}
              {node.poachability != null && (
                <ScoreBar label="Poachability" value={node.poachability} color="#f59e0b" />
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default function ReportView({ mapData, form }) {
  function handleCopyReport() {
    const markdown = formatMarkdownReport(form, mapData);
    navigator.clipboard.writeText(markdown);
  }

  function handlePrint() {
    window.print();
  }

  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="report-view">
      {/* Action bar */}
      <div className="flex items-center gap-2 mb-6 print:hidden">
        <button
          onClick={handleCopyReport}
          className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-600 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
        >
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <rect x="9" y="9" width="13" height="13" rx="2" ry="2" strokeWidth="2" />
            <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" strokeWidth="2" />
          </svg>
          Copy as Markdown
        </button>
        <button
          onClick={handlePrint}
          className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-600 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
        >
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path d="M6 9V2h12v7M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2M6 14h12v8H6z" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          Print
        </button>
      </div>

      {/* Report header */}
      <div className="mb-8 pb-6 border-b border-gray-300">
        <h1 className="text-xl font-bold text-gray-900 mb-1">Talent Landscape Report</h1>
        <div className="space-y-0.5 text-sm text-gray-600">
          <div>
            <strong>Role:</strong> {form.role}{form.seniority ? ` (${form.seniority})` : ""}
          </div>
          {form.company && (
            <div><strong>Hiring Company:</strong> {form.company}</div>
          )}
          {form.location && (
            <div><strong>Location:</strong> {form.location}</div>
          )}
          {form.skills.length > 0 && (
            <div><strong>Skills:</strong> {form.skills.join(", ")}</div>
          )}
          <div className="text-xs text-gray-400 pt-1">{date}</div>
        </div>
      </div>

      {/* Report sections */}
      <ReportSection title="Target Companies" catKey="companies" nodes={mapData.companies} />
      <ReportSection title="Adjacent Talent Pools" catKey="adjacent" nodes={mapData.adjacent} />
      <ReportSection title="Wildcard Bets" catKey="wildcards" nodes={mapData.wildcards} />
      <ReportSection title="Target Titles" catKey="titles" nodes={mapData.titles} />

      {/* Disclaimer */}
      <div className="mt-8 pt-4 border-t border-gray-200 text-xs text-gray-400 italic">
        AI-generated talent intelligence. Verify all company details and hiring signals before outreach.
      </div>
    </div>
  );
}
